### ISSUE TITLE
indiremedim de  ya yardım eder misin indirme yeri neden yok yada ben mi indiremiyorum 

### ISSUE THREAD

**Issue by mazlum01478** [Eld3rly/gartic.io-raid-tools#1]
indiremedim de  ya yardım eder misin indirme yeri neden yok yada ben mi indiremiyorum

**Comment by Eld3rly** [comment]
Komut dosyasını yükleme talimatlarını [README.md](https://github.com/Eld3rly/gartic.io-raid-tools/blob/main/README.md)'de bulabilirsiniz, talimatları izleyerek kuramazsanız bana sorununuz hakkında daha fazla bilgi gönderin.
