### ISSUE TITLE
where to call votekick function?

### ISSUE THREAD

**Issue by wasdcx24** [Eld3rly/gartic.io-raid-tools#3]
i use bot.voteKick in index.js and this.voteKick in client.js but nothing happens. where to call function?

**Comment by Eld3rly** [comment]
The **voteKick** function must be used **after the bot has connected** to the room.
example:
```js
const Client = require("./client.js");
const bot = new Client({id: 1, invite: 1, name: `1`})
bot.on("roomConnected", _ =>{
    bot.voteKick(1)
})
bot.connect()
```
